openapi: 3.0.1
info:
  title: Payment Methods
  description: |-
    Get a list of a store's enabled payment methods. For processing payments, see [Payment Processing API](/api-docs/payments/payments-api-overview).

    ## Authentication

    Authenticate requests by including an [OAuth](/api-docs/getting-started/authentication/rest-api-authentication) `access_token` in the request header.

    ```http
    GET https://api.bigcommerce.com/stores/{{STORE_HASH}}/v2/{{ENDPOINT}}
    Content-Type: application/json
    X-Auth-Token: {{ACCESS_TOKEN}}
    ```

    ### OAuth Scopes
    |  **UI Name** | **Permission** | **Parameter** |
    | --- | --- | --- |
    |  Information & Settings | read-only | `store_payments_methods_read` |
  termsOfService: ""
  license:
    name: ""
  version: ""
servers:
- url: https://api.bigcommerce.com/
security:
- X-Auth-Token: []
tags:
- name: Payment Methods
paths:
  /stores/{store_hash}/v2/payments/methods:
    get:
      tags:
      - Payment Methods
      summary: Get All Payment Methods
      description: "Gets the list of enabled payment methods. Default sorting is by\
        \ payment method, alphabetically from A to Z.\n\n<!-- theme: info -->\n> ####\
        \ Note:\n> Avoid using this API operation if possible. It is not supported;\
        \ therefore, all enabled providers may not appear.\n "
      parameters:
      - name: store_hash
        in: path
        required: true
        schema:
          type: string
      - name: Accept
        in: header
        required: true
        schema:
          type: string
          default: application/json
      - name: Content-Type
        in: header
        required: true
        schema:
          type: string
          default: application/json
      - name: page
        in: query
        description: Optional filter param `/api/v2/payments/methods?page={number}`
        schema:
          exclusiveMaximum: false
          exclusiveMinimum: false
          type: number
      - name: limit
        in: query
        description: Optional filter param `/api/v2/payments/methods?limit={count}`
        schema:
          exclusiveMaximum: false
          exclusiveMinimum: false
          type: number
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/payment_Base'
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
components:
  schemas:
    payment_Base:
      title: payment_Base
      type: object
      properties:
        code:
          type: string
          description: Unique platform-wide code identifying the payment method.
          example: squarev2
        name:
          type: string
          description: Descriptive name of the payment method.
          example: Square
        test_mode:
          type: boolean
          description: Determines whether the payment gateway is in test mode. Always
            false for offline payment methods.
          example: false
      example:
        code: squarev2
        name: Square
        test_mode: false
      x-internal: false
  responses:
    paymentCollection_Resp:
      description: ""
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/payment_Base'
  securitySchemes:
    X-Auth-Token:
      type: apiKey
      description: "### OAuth Scopes\n|  **UI Name** | **Permission** | **Parameter**\
        \ |\n| --- | --- | --- |\n|  Information & Settings | read-only | `store_payments_methods_read`\
        \ |\n\n### Headers\n\n|Header|Parameter|Description|\n|-|-|-|\n|`X-Auth-Token`|`access_token\
        \ `|Obtained by creating an API account or installing an app in a BigCommerce\
        \ control panel.|\n\n### Example\n\n```http\nGET /stores/{store_hash}/v3/catalog/summary\n\
        host: api.bigcommerce.com\nContent-Type: application/json\nX-Auth-Token: {access_token}\n\
        ```\n\n* For more information on Authenticating BigCommerce APIs, see: [Authentication](/api-docs/getting-started/authentication). "
      name: X-Auth-Token
      in: header
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
